### ISSUE TITLE
I don;t boodk?

### ISSUE THREAD

**Issue by mcclowes** [WillJCJ/tdd-book#1]

**Comment by WillJCJ** [comment]
![rockhopper](https://cloud.githubusercontent.com/assets/3356529/19275646/354e0358-8fcc-11e6-8d60-630f9e4aa6ea.jpg)

**Comment by mcclowes** [comment]
Ahhhhh, now is see!

Thanks for the help xxx

**Comment by WillJCJ** [comment]
yes ok

**Comment by WillJCJ** [comment]
yes ok
